name: Auto Merge Dependabot Pull Request

on: pull_request

jobs:
  auto-merge:
    if: ${{github.actor == 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    env:
      GITHUB_TOKEN: ${{github.token}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Merge Dependabot Pull Request
        run: gh pr merge "${GITHUB_HEAD_REF}" --merge
