name: Auto Merge Dependabot Pull Requests

on: pull_request

jobs:
  auto-merge:
    if: ${{github.actor == 'dependabot[bot]'}}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    env:
      GITHUB_TOKEN: ${{github.token}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: fetch metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2

      - name: merge automaticaly if patch update
        if: ${{steps.metadata.outputs.dependency-type == 'version-update:semver-patch'}}
        run: gh pr merge ${GITHUB_HEAD_REF} --merge
